name: Publish release

permissions:
  pull-requests: write
  contents: write
  id-token: write     # Required for OIDC token exchange / trusted publishing

on:
  push:
    branches:
      - main

jobs:
  release-plz-release:
    if: github.repository_owner == 'rcoh'
    name: Release-plz release
    runs-on: ubuntu-latest
    environment: release

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Authenticate to crates.io
        uses: rust-lang/crates-io-auth-action@v1
        id: auth
      - name: Run release-plz
        uses: release-plz/action@v0.5.102
        with:
          command: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
